name: "Certificates sync"

on:
  workflow_call:
    inputs:
      DIRECTORY:
        type: string
        required: true
        description: 'Working directory'
      APP_TYPE:
        type: string
        required: true
        description: 'App type for which certificates should be synced'
      BUILD_TYPE:
        type: string
        required: true
        description: 'Build type for which certificates should be synced'
    secrets:        
      GCP_SERVICE_ACCOUNT:
        required: true

jobs:
  check-certificates:
    runs-on: [ macos-latest ]
    timeout-minutes: 20
    steps:

      - id: checkout
        name: 'Checkout'
        uses: actions/checkout@v2
        with:
          path: ${{ inputs.DIRECTORY }}
          clean: true

      - id: create-gc-auth-json
        name: "Save gc auth data to fastlane folder"
        working-directory: ${{ inputs.DIRECTORY }}
        shell: bash
        run: |
          mkdir Fastlane && touch Fastlane/gc_keys.json && cat <<< "${{ secrets.GCP_SERVICE_ACCOUNT }}" > Fastlane/gc_keys.json         

      - id: sync_prod_app_ceritficates
        name: 'Sync certificates for prod App'
        shell: bash
        if: inputs.APP_TYPE == 'prod'
        working-directory: ${{ inputs.DIRECTORY }}
        run: |
          echo "Sync certificates for prod App"
          fastlane sync_certificates build_type:${{ inputs.BUILD_TYPE }} identifiers:"com.intergiro.app,com.intergiro.app.notificationService"

      - id: sync_dev_app_ceritficates
        name: 'Sync certificates for dev App'
        shell: bash
        if: inputs.APP_TYPE == 'dev'
        working-directory: ${{ inputs.DIRECTORY }}
        run: |
          echo "Sync certificates for dev App"
          fastlane sync_certificates build_type:${{ inputs.BUILD_TYPE }} identifiers:"com.intergiro.app-dev,com.intergiro.app-dev.notificationService"
