name: njsscan sarif

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: false
        default: europe-docker.pkg.dev/ftcs-production/infrastructure/node-build-tools:16
    secrets:
      DOCKER_REGISTRY_USER:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true
jobs:
  njsscan:
    name: Njsscan
    runs-on: [self-hosted, common]
    container:
      image: ${{ inputs.image }}
      credentials:
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: 'Workaround permissions issue'
      run: chown $(whoami):$(whoami) -R .

    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'
